In [55]:
import os
import yaml
import pandas as pd
import chardet #encoding-detection

yaml -> merge -> csv(file)

In [56]:
main_folder = "C:\prj_stock_analysis\datas\original_data"
all_yaml_data = []

def detect_encoding(file_path):
    with open(file_path, 'rb') as f:
        result = chardet.detect(f.read(10000))
    return result['encoding']

for folder_path, subfolders, files in os.walk(main_folder):
    for yaml_file in files:
        if yaml_file.endswith(('.yaml', '.yml')):
            file_path = os.path.join(folder_path, yaml_file)
            try:
                encoding = detect_encoding(file_path)
                with open(file_path, 'r', encoding=encoding) as f:
                    data = yaml.safe_load(f)
                    if isinstance(data, list):
                        all_yaml_data.extend(data)
                    elif isinstance(data, dict):
                        all_yaml_data.append(data)
            except Exception as e:
                print(f"Error reading {file_path}: {e}")

# Save to CSV
if all_yaml_data:
    df = pd.DataFrame(all_yaml_data)
    output_path = os.path.join(r"C:\prj_stock_analysis\datas","aligned.csv")
    df.to_csv(output_path, index=False)
    print(f"saved and the link here {output_path}")
else:
    print("no valid yaml")

<>:1: SyntaxWarning: invalid escape sequence '\p'
<>:1: SyntaxWarning: invalid escape sequence '\p'
C:\Users\123\AppData\Local\Temp\ipykernel_5068\1550231298.py:1: SyntaxWarning: invalid escape sequence '\p'
  main_folder = "C:\prj_stock_analysis\datas\original_data"

saved and the link here C:\prj_stock_analysis\datas\aligned.csv

basic checks

In [57]:
df = pd.read_csv(r"C:\prj_stock_analysis\datas\aligned.csv")
df.head(25)

,Ticker,close,date,high,low,month,open,volume
0,SBIN,602.95,2023-10-03 05:30:00,604.90,589.60,2023-10,596.60,15322196
1,BAJFINANCE,7967.60,2023-10-03 05:30:00,7975.50,7755.00,2023-10,7780.80,944555
2,TITAN,3196.25,2023-10-03 05:30:00,3212.50,3114.40,2023-10,3148.80,1007308
3,ITC,439.75,2023-10-03 05:30:00,442.90,439.25,2023-10,441.00,7481883
4,TCS,3513.85,2023-10-03 05:30:00,3534.20,3480.10,2023-10,3534.20,1948148
5,LT,3073.25,2023-10-03 05:30:00,3077.45,2995.10,2023-10,3040.50,3254492
6,TATACONSUM,861.20,2023-10-03 05:30:00,868.75,853.49,2023-10,859.32,1168848
7,RELIANCE,1159.08,2023-10-03 05:30:00,1167.80,1158.00,2023-10,1164.97,8859056
8,HCLTECH,1238.70,2023-10-03 05:30:00,1256.70,1222.70,2023-10,1232.50,2162636
9,JSWSTEEL,770.25,2023-10-03 05:30:00,776.55,768.00,2023-10,776.55,1099773
10,ULTRACEMCO,8304.90,2023-10-03 05:30:00,8377.00,8221.20,2023-10,8289.00,454402
11,POWERGRID,199.55,2023-10-03 05:30:00,200.00,196.90,2023-10,198.75,10830728
12,INFY,1434.00,2023-10-03 05:30:00,1437.00,1420.30,2023-10,1436.05,4181867
13,TRENT,2059.10,2023-10-03 05:30:00,2086.30,2052.00,2023-10,2074.30,543387
14,BHARTIARTL,925.30,2023-10-03 05:30:00,928.25,916.05,2023-10,918.25,4338272
15,TATAMOTORS,620.45,2023-10-03 05:30:00,632.65,618.60,2023-10,632.60,6894577
16,WIPRO,405.45,2023-10-03 05:30:00,408.10,403.60,2023-10,406.45,2864052
17,TECHM,1216.20,2023-10-03 05:30:00,1230.70,1212.55,2023-10,1220.60,1622290
18,NTPC,241.20,2023-10-03 05:30:00,246.70,240.55,2023-10,244.35,14885044
19,HINDUNILVR,2468.90,2023-10-03 05:30:00,2499.00,2461.80,2023-10,2490.00,1585626
20,APOLLOHOSP,5118.95,2023-10-03 05:30:00,5154.95,5066.00,2023-10,5138.95,268482
21,M&M,1537.40,2023-10-03 05:30:00,1598.00,1533.05,2023-10,1597.20,3436776
22,GRASIM,1913.84,2023-10-03 05:30:00,1931.32,1899.10,2023-10,1920.46,591326
23,ICICIBANK,940.30,2023-10-03 05:30:00,951.60,939.00,2023-10,951.60,11131636
24,ADANIENT,2387.25,2023-10-03 05:30:00,2424.90,2372.00,2023-10,2418.00,2019899

In [58]:
df_copy = df.copy()
df.columns

Index(['Ticker', 'close', 'date', 'high', 'low', 'month', 'open', 'volume'], dtype='object')

Data time column(modification) -> split columns

In [59]:
df_copy['date']=pd.to_datetime(df_copy['date'])

In [60]:
df_copy['Day']=df_copy['date'].dt.day
df_copy['Month']=df_copy['date'].dt.month
df_copy['Year']=df_copy['date'].dt.year
df_copy['Time'] = df_copy['date'].dt.time

In [61]:
df_copy = df_copy.drop("month", axis=1)
df_copy = df_copy.drop("date", axis=1)

In [ ]:
df_copy.head()

Sorting -> grouping -> individual ticker csv's

In [ ]:
output_folder = r"C:\prj_stock_analysis\datas\aggregated_data_1"
os.makedirs(output_folder, exist_ok=True)


df_copy = df_copy.sort_values(by=['Month','Day'])


for ticker, group in df_copy.groupby('Ticker'):
    file_name = f"{ticker}.csv"
    output_path = os.path.join(output_folder, file_name)
    group.to_csv(output_path, index=False)

print("successful")

succesful

In [67]:
c = ''
for i in range(10):
    c += b'\xF0\x9F\x98\x8A'.decode('utf-8')
print("Completed a part", c)

Completed a part 😊😊😊😊😊😊😊😊😊😊